apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
    spec:
      containers:
        - name: secrets
          image: pbgnz/mls-secrets:latest